### ISSUE TITLE
Dict location not applying during scan

### ISSUE THREAD

**Issue by 2raziel3** [nccgroup/hashcrack#3]
Hi,

Saw your talk at Bsides and wanted to give this a try.
However when i run the first recommended scan;

python3 hashcrack.py -i <input file>

The scan will start and will crack some hashes, using your example ntlm.txt but then
the scan will run a new hashcat query looking in dict/<DICTIONARY> and ./hashcat-5.1.0/rules/rules/<RULES>
Even though I have configured the paths in hashcrack-unix.cfg , also tried in hashcrack.cfg

Any advice would be appreciated.

**Comment by jamieriden** [comment]
can you send me the full command and output please? ie. paste everything from python3 hashcrack.py -i ... onwards. Send to jamie.riden@nccgroup.com if you don't want to paste here.

**Comment by 2raziel3** [comment]
My bad, was missing the output erroring on the config file so it is failling to default dicts and rules.
I have sent the config file to the email provided.

**Comment by jamieriden** [comment]
sorry, did we sort this out, or was it someone else emailing me at the same
time?

**Comment by 2raziel3** [comment]
Sorry Jamie,

This was sorted, it seemed likt the config was not applying from the hashcrack-unix.cfg file.
When i transferred the same config to hashcrack.cfg all was good.
Thanks for your help.

**Comment by jamieriden** [comment]
No worries - I should probably have called that hashcrack-unix-example.cfg or something. Thanks!
